development:
  adapter: postgresql
  database: alfinanceiro_development
  username: postgres
  password: adminroot
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: alfinanceiro_production
  username: postgres
  password: adminroot
  host: localhost
  encoding: UTF8

